apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-fleet-manager-demo-app
  labels:
    app.kubernetes.io/name: aks-fleet-manager-demo-app
    kubernetes.azure.com/generator: draft
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: aks-fleet-manager-demo-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: aks-fleet-manager-demo-app
    spec:
      containers:
        - name: aks-fleet-manager-demo-app
          image: acritalynorth01.azurecr.io/image-workflow-1767086088668:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: aks-fleet-manager-demo-app-config
            - secretRef:
                name: secret-ref
                optional: true
          livenessProbe:
            tcpSocket:
              port: 8000
          readinessProbe:
            tcpSocket:
              port: 8000
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 1
            successThreshold: 1
            initialDelaySeconds: 3
          startupProbe:
            tcpSocket:
              port: 8000
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
            successThreshold: 1
            initialDelaySeconds: 0
